name: CI & Release

on:
  push:
    tags: ["v*"]
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  GO_VERSION: "1.24"

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./...

  release:
    name: Build & Publish Binaries
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build for ${{ matrix.os }}_${{ matrix.arch }}
        run: |
          export GOOS=${{ matrix.os }}
          export GOARCH=${{ matrix.arch }}
          OUTPUT="terraform-provider-digesttracker_${{ github.ref_name }}_${GOOS}_${GOARCH}"
          [ "$GOOS" = "windows" ] && OUTPUT="$OUTPUT.exe"
          go build -o "$OUTPUT"
          mkdir -p dist
          zip -j "dist/${OUTPUT}.zip" "$OUTPUT"

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
